language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: release
      script:
        - npm run test || travis_terminate 1;
        - npm run build:server:prod || travis_terminate 1;

      deploy:
        - provider: s3
          access_key_id: '$AWS_ACCESS_KEY'
          secret_access_key: '$AWS_SECRET_KEY'
          bucket: 'cyrille-dragonfly'
          acl: public_read
          skip_cleanup: true
          local_dir: dist
          upload-dir: '$TRAVIS_BUILD_NUMBER'
          on:
            all_branches: true
