version: "3"
services:
  # app:
  #   build: .
    # depends_on:
    #   - postgres
    # links:
    #   - postgres
    # environment:
    #   DATABASE_URL: postgres://user:pass@postgres:5432/db
    #   NODE_ENV: development
    #   PORT: 3000
    # ports:
    #   - "3000:3000"
    # command: ls -a # npm run start
    # volumes:
    #   - .:/app

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
